#!/usr/bin/env bash

# Enforce univ-cotedazur email

regex='.*?@etu\.univ-cotedazur\.fr'
email="$(git config user.email)"


if ! $(echo "$email" | grep -Eq  "$regex")
then
	echo "Invalid email"
	exit 1
else
	exit 0
fi


